### ISSUE TITLE
Cachemanager.close should Unregister the cache instance from MBean server

### ISSUE THREAD

**Issue by rcbose** [ocafebabe/guava-jcache#3]
Cachemanager.close should Unregister the cache instance from MBean server.

Right now the MBean exist even after closing the Cache, resulting failure when you re-create the cache.

Following is the code to reproduce the issue:

`CacheManager cacheManager = Caching.getCachingProvider(GuavaCachingProvider.class.getName()).getCacheManager();
    MutableConfiguration<String, String> config = new MutableConfiguration<>();
    config.setStoreByValue(false);
    config.setManagementEnabled(true);
    Cache<String, String> cache =  cacheManager.createCache("test", config);
    cache.put("key1", "value1");
    System.out.println(cache.get("key1"));
    cacheManager.close();

    cacheManager = Caching.getCachingProvider(GuavaCachingProvider.class.getName()).getCacheManager();

    cache =  cacheManager.createCache("test", config);
    cache.put("key1", "value1");
    System.out.println(cache.get("key1"));`

**Comment by ocafebabe** [comment]
Thanks for bringing this issue to my attention! I'll have a look at it!
